import {
  Target,
  Search,
  Compass,
  Eye,
  Users,
  UserCheck,
  MessageSquare,
  Mail,
  Send,
  Inbox,
  Settings,
  RefreshCw,
  PlusCircle,
  CheckCircle2,
  Check,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Clock,
  Calendar,
  History,
  Folder,
  FolderOpen,
  File,
  FileText,
  BookOpen,
  Archive,
  ShieldCheck,
  Shield,
  Lock,
  Unlock,
  Key,
  Lightbulb,
  Sparkles,
  Zap,
  Star,
  Heart,
  Award,
  Trophy,
  Gift,
  Bell,
  TrendingUp,
  Activity,
  BarChart,
  PieChart,
  Layout,
  Home,
  Phone,
  MapPin,
  Globe,
  Image as ImageIcon,
  Video,
  Music,
  Camera,
  Mic,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Download,
  Upload,
  Share2,
  Link,
  Copy,
  Tag,
  Bookmark,
  Filter,
  Flag,
  Code,
  Database,
  Server,
  Cloud,
  Wifi,
  Radio,
  Tv,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Printer,
  Battery,
  Bluetooth,
  Cast,
  Package,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Briefcase,
  Building,
} from "lucide-react";
import { Label } from "./ui/label";

// Liste étendue des icônes disponibles
export const availableIcons = [
  { name: "Target", label: "Cible" },
  { name: "Search", label: "Recherche" },
  { name: "Compass", label: "Boussole" },
  { name: "Eye", label: "Observer" },
  { name: "Users", label: "Utilisateurs" },
  { name: "UserCheck", label: "Utilisateur Vérifié" },
  { name: "MessageSquare", label: "Message" },
  { name: "Mail", label: "Email" },
  { name: "Send", label: "Envoyer" },
  { name: "Inbox", label: "Boîte de réception" },
  { name: "Settings", label: "Paramètres" },
  { name: "RefreshCw", label: "Actualiser" },
  { name: "PlusCircle", label: "Ajouter" },
  { name: "CheckCircle2", label: "Validation" },
  { name: "Check", label: "Cocher" },
  { name: "XCircle", label: "Annuler" },
  { name: "AlertCircle", label: "Alerte" },
  { name: "Info", label: "Information" },
  { name: "HelpCircle", label: "Aide" },
  { name: "Clock", label: "Horloge" },
  { name: "Calendar", label: "Calendrier" },
  { name: "History", label: "Historique" },
  { name: "Folder", label: "Dossier" },
  { name: "FolderOpen", label: "Dossier Ouvert" },
  { name: "File", label: "Fichier" },
  { name: "FileText", label: "Document" },
  { name: "BookOpen", label: "Livre" },
  { name: "Archive", label: "Archive" },
  { name: "ShieldCheck", label: "Sécurité" },
  { name: "Shield", label: "Bouclier" },
  { name: "Lock", label: "Verrouillé" },
  { name: "Unlock", label: "Déverrouillé" },
  { name: "Key", label: "Clé" },
  { name: "Lightbulb", label: "Idée" },
  { name: "Sparkles", label: "Étoiles" },
  { name: "Zap", label: "Rapide" },
  { name: "Star", label: "Favori" },
  { name: "Heart", label: "Apprécier" },
  { name: "Award", label: "Récompense" },
  { name: "Trophy", label: "Trophée" },
  { name: "Gift", label: "Cadeau" },
  { name: "Bell", label: "Notification" },
  { name: "TrendingUp", label: "Tendance" },
  { name: "Activity", label: "Activité" },
  { name: "BarChart", label: "Graphique" },
  { name: "PieChart", label: "Camembert" },
  { name: "Layout", label: "Mise en page" },
  { name: "Home", label: "Accueil" },
  { name: "Phone", label: "Téléphone" },
  { name: "MapPin", label: "Localisation" },
  { name: "Globe", label: "Internet" },
  { name: "Image", label: "Image" },
  { name: "Video", label: "Vidéo" },
  { name: "Music", label: "Musique" },
  { name: "Camera", label: "Caméra" },
  { name: "Mic", label: "Microphone" },
  { name: "Volume2", label: "Volume" },
  { name: "Play", label: "Lecture" },
  { name: "Pause", label: "Pause" },
  { name: "SkipForward", label: "Suivant" },
  { name: "SkipBack", label: "Précédent" },
  { name: "Download", label: "Télécharger" },
  { name: "Upload", label: "Charger" },
  { name: "Share2", label: "Partager" },
  { name: "Link", label: "Lien" },
  { name: "Copy", label: "Copier" },
  { name: "Tag", label: "Étiquette" },
  { name: "Bookmark", label: "Signet" },
  { name: "Filter", label: "Filtrer" },
  { name: "Flag", label: "Drapeau" },
  { name: "Code", label: "Code" },
  { name: "Database", label: "Base de données" },
  { name: "Server", label: "Serveur" },
  { name: "Cloud", label: "Cloud" },
  { name: "Wifi", label: "Wi-Fi" },
  { name: "Radio", label: "Radio" },
  { name: "Tv", label: "Télévision" },
  { name: "Smartphone", label: "Smartphone" },
  { name: "Tablet", label: "Tablette" },
  { name: "Laptop", label: "Ordinateur" },
  { name: "Monitor", label: "Moniteur" },
  { name: "Printer", label: "Imprimante" },
  { name: "Battery", label: "Batterie" },
  { name: "Bluetooth", label: "Bluetooth" },
  { name: "Cast", label: "Diffuser" },
  { name: "Package", label: "Paquet" },
  { name: "ShoppingCart", label: "Panier" },
  { name: "CreditCard", label: "Carte bancaire" },
  { name: "DollarSign", label: "Dollar" },
  { name: "Briefcase", label: "Porte-documents" },
  { name: "Building", label: "Bâtiment" },
];

// Fonction pour obtenir le composant d'icône
export const getIconComponent = (iconName: string) => {
  const iconMap: Record<string, any> = {
    Target,
    Search,
    Compass,
    Eye,
    Users,
    UserCheck,
    MessageSquare,
    Mail,
    Send,
    Inbox,
    Settings,
    RefreshCw,
    PlusCircle,
    CheckCircle2,
    Check,
    XCircle,
    AlertCircle,
    Info,
    HelpCircle,
    Clock,
    Calendar,
    History,
    Folder,
    FolderOpen,
    File,
    FileText,
    BookOpen,
    Archive,
    ShieldCheck,
    Shield,
    Lock,
    Unlock,
    Key,
    Lightbulb,
    Sparkles,
    Zap,
    Star,
    Heart,
    Award,
    Trophy,
    Gift,
    Bell,
    TrendingUp,
    Activity,
    BarChart,
    PieChart,
    Layout,
    Home,
    Phone,
    MapPin,
    Globe,
    Image: ImageIcon,
    Video,
    Music,
    Camera,
    Mic,
    Volume2,
    Play,
    Pause,
    SkipForward,
    SkipBack,
    Download,
    Upload,
    Share2,
    Link,
    Copy,
    Tag,
    Bookmark,
    Filter,
    Flag,
    Code,
    Database,
    Server,
    Cloud,
    Wifi,
    Radio,
    Tv,
    Smartphone,
    Tablet,
    Laptop,
    Monitor,
    Printer,
    Battery,
    Bluetooth,
    Cast,
    Package,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Briefcase,
    Building,
  };
  return iconMap[iconName] || Target;
};

// Fonction pour obtenir l'icône rendue
export const getIcon = (iconName: string) => {
  const IconComponent = getIconComponent(iconName);
  return <IconComponent className="w-5 h-5 text-[var(--accent)]" />;
};

interface IconSelectorProps {
  value: string;
  onChange: (iconName: string) => void;
}

export function IconSelector({ value, onChange }: IconSelectorProps) {
  return (
    <div className="space-y-2">
      <Label className="text-[var(--foreground)]">Icône</Label>
      <div className="flex items-center gap-3 p-3 border border-[var(--border)] rounded-[var(--radius)] bg-[var(--card)]">
        <div className="shrink-0">{getIcon(value)}</div>
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="flex-1 bg-transparent border-none outline-none text-[var(--foreground)] cursor-pointer"
        >
          {availableIcons.map((iconOption) => (
            <option key={iconOption.name} value={iconOption.name}>
              {iconOption.label}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
}
