// Liste étendue des icônes disponibles pour les tâches
export const availableIcons = [
  { name: "Target", label: "Cible" },
  { name: "Search", label: "Recherche" },
  { name: "Compass", label: "Boussole" },
  { name: "Eye", label: "Observer" },
  { name: "Users", label: "Utilisateurs" },
  { name: "UserCheck", label: "Utilisateur Vérifié" },
  { name: "MessageSquare", label: "Message" },
  { name: "Mail", label: "Email" },
  { name: "Send", label: "Envoyer" },
  { name: "Inbox", label: "Boîte de réception" },
  { name: "Settings", label: "Paramètres" },
  { name: "RefreshCw", label: "Actualiser" },
  { name: "PlusCircle", label: "Ajouter" },
  { name: "CheckCircle2", label: "Validation" },
  { name: "Check", label: "Cocher" },
  { name: "XCircle", label: "Annuler" },
  { name: "AlertCircle", label: "Alerte" },
  { name: "Info", label: "Information" },
  { name: "HelpCircle", label: "Aide" },
  { name: "Clock", label: "Horloge" },
  { name: "Calendar", label: "Calendrier" },
  { name: "History", label: "Historique" },
  { name: "Folder", label: "Dossier" },
  { name: "FolderOpen", label: "Dossier Ouvert" },
  { name: "File", label: "Fichier" },
  { name: "FileText", label: "Document" },
  { name: "BookOpen", label: "Livre" },
  { name: "Archive", label: "Archive" },
  { name: "ShieldCheck", label: "Sécurité" },
  { name: "Shield", label: "Bouclier" },
  { name: "Lock", label: "Verrouillé" },
  { name: "Unlock", label: "Déverrouillé" },
  { name: "Key", label: "Clé" },
  { name: "Lightbulb", label: "Idée" },
  { name: "Sparkles", label: "Étoiles" },
  { name: "Zap", label: "Rapide" },
  { name: "Star", label: "Favori" },
  { name: "Heart", label: "Apprécier" },
  { name: "Award", label: "Récompense" },
  { name: "Trophy", label: "Trophée" },
  { name: "Gift", label: "Cadeau" },
  { name: "Bell", label: "Notification" },
  { name: "TrendingUp", label: "Tendance" },
  { name: "Activity", label: "Activité" },
  { name: "BarChart", label: "Graphique" },
  { name: "PieChart", label: "Camembert" },
  { name: "Layout", label: "Mise en page" },
  { name: "Home", label: "Accueil" },
  { name: "Phone", label: "Téléphone" },
  { name: "MapPin", label: "Localisation" },
  { name: "Globe", label: "Internet" },
  { name: "Image", label: "Image" },
  { name: "Video", label: "Vidéo" },
  { name: "Music", label: "Musique" },
  { name: "Camera", label: "Caméra" },
  { name: "Mic", label: "Microphone" },
  { name: "Volume2", label: "Volume" },
  { name: "Play", label: "Lecture" },
  { name: "Pause", label: "Pause" },
  { name: "SkipForward", label: "Suivant" },
  { name: "SkipBack", label: "Précédent" },
  { name: "Download", label: "Télécharger" },
  { name: "Upload", label: "Charger" },
  { name: "Share2", label: "Partager" },
  { name: "Link", label: "Lien" },
  { name: "Copy", label: "Copier" },
  { name: "Tag", label: "Étiquette" },
  { name: "Bookmark", label: "Signet" },
  { name: "Filter", label: "Filtrer" },
  { name: "Flag", label: "Drapeau" },
  { name: "Code", label: "Code" },
  { name: "Database", label: "Base de données" },
  { name: "Server", label: "Serveur" },
  { name: "Cloud", label: "Cloud" },
  { name: "Wifi", label: "Wi-Fi" },
  { name: "Radio", label: "Radio" },
  { name: "Tv", label: "Télévision" },
  { name: "Smartphone", label: "Smartphone" },
  { name: "Tablet", label: "Tablette" },
  { name: "Laptop", label: "Ordinateur" },
  { name: "Monitor", label: "Moniteur" },
  { name: "Printer", label: "Imprimante" },
  { name: "Battery", label: "Batterie" },
  { name: "Bluetooth", label: "Bluetooth" },
  { name: "Cast", label: "Diffuser" },
  { name: "Package", label: "Paquet" },
  { name: "ShoppingCart", label: "Panier" },
  { name: "CreditCard", label: "Carte bancaire" },
  { name: "DollarSign", label: "Dollar" },
  { name: "Briefcase", label: "Porte-documents" },
  { name: "Building", label: "Bâtiment" },
];
